services:
  - type: web
    name: vibe-check-server
    env: node
    buildCommand: cd server && npm install && npx prisma generate
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: vibe-check-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production 