services:
  - type: web
    name: vibe-check-server
    env: node
    buildCommand: |
      cd server
      npm install
      echo "Compiling TypeScript..."
      npm run build
      echo "Build completed, checking contents..."
      ls -la dist/src/
      ls -la dist/lib/
      echo "Generating Prisma client..."
      npx prisma generate
      npx prisma migrate deploy
    startCommand: |
      cd server
      echo "Starting server in production mode..."
      NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: vibe-check-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: vibe-check-client
    env: static
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://vibe-check-server.onrender.com/api

databases:
  - name: vibe-check-db
    databaseName: vibecheck
    plan: free 